# This workflow will build a .NET Core project and deploy it to an Azure Functions App on Windows or Linux when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure Functions app.
# For instructions see https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-csharp?tabs=in-process
#
# To configure this workflow:
# 1. Set up the following secrets in your repository:
#   - AZURE_FUNCTIONAPP_PUBLISH_PROFILE
# 2. Change env variables for your configuration.
#
# For more information on:
#   - GitHub Actions for Azure: https://github.com/Azure/Actions
#   - Azure Functions Action: https://github.com/Azure/functions-action
#   - Publish Profile: https://github.com/Azure/functions-action#using-publish-profile-as-deployment-credential-recommended
#   - Azure Service Principal for RBAC: https://github.com/Azure/functions-action#using-azure-service-principal-for-rbac-as-deployment-credential
#
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples/tree/master/FunctionApp

name: Deploy DotNet project to Azure Function App

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  AZURE_FUNCTIONAPP_NAME: 'func-cus'   # set this to your function app name on Azure
  # Point this to the folder that contains your Function App csproj (update if your project is in a subfolder)
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'SqlManagedIdentity'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # For Linux, use ubuntu-latest
    environment: dev
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Login via Azure CLI'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup DotNet ${{ vars.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash # For Linux, use bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: Deploy Bicep file
        id: bicep_deployment
        uses: azure/arm-deploy@v2
        with:
          template: ./SqlManagedIdentity/Deployment/deploy.bicep
          failOnStdErr: false
          scope: 'subscription'
          region: 'Central US'

      - name: Use Bicep Outputs
        run: |
          echo "Function App Id: ${{ steps.bicep_deployment.outputs.functionPrincipalId }}"        

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
      
      # dacpac to run migration sql
      - name: 'Sql Migration'
        uses: azure/sql-action@v2.3
        with:
          connection-string: 'Server=tcp:sqlmanagedidentitycus.database.windows.net,1433;Initial Catalog=sql-db-todo;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;Authentication="Active Directory Default";'
          path: ./SqlManagedIdentity/Migration1.sql

      - name: Execute PowerShell script
        run: ./SqlManagedIdentity/Deployment//GenerateSqlScript.ps1 -appName "'func-cus'" -principalId '${{ steps.bicep_deployment.outputs.functionPrincipalId }}'
        shell: pwsh
        
  # dacpac to grant function app permissions to db