# This workflow will build a .NET Core project and deploy it to an Azure Functions App on Windows or Linux when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure Functions app.
# For instructions see https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-csharp?tabs=in-process
#
# To configure this workflow:
# 1. Set up the following secrets in your repository:
#   - AZURE_FUNCTIONAPP_PUBLISH_PROFILE
# 2. Change env variables for your configuration.
#
# For more information on:
#   - GitHub Actions for Azure: https://github.com/Azure/Actions
#   - Azure Functions Action: https://github.com/Azure/functions-action
#   - Publish Profile: https://github.com/Azure/functions-action#using-publish-profile-as-deployment-credential-recommended
#   - Azure Service Principal for RBAC: https://github.com/Azure/functions-action#using-azure-service-principal-for-rbac-as-deployment-credential
#
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples/tree/master/FunctionApp

name: Deploy DotNet project to Azure Function App

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  AZURE_FUNCTIONAPP_NAME: 'func-cus'   # set this to your function app name on Azure
  # Point this to the folder that contains your Function App csproj (update if your project is in a subfolder)
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'SqlManagedIdentity'
  CONNECTION_STRING: 'Server=tcp:sqlmanagedidentitycus.database.windows.net,1433;Initial Catalog=todo;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;Authentication="Active Directory Default";'
                 
jobs:
  build-reusable:
    uses: ./.github/workflows/common-build-steps.yml
    with:
      AZURE_FUNCTIONAPP_PACKAGE_PATH: ${{env.AZURE_FUNCTIONAPP_PACKAGE_PATH}}
      AZURE_FUNCTIONAPP_NAME: ${{env.AZURE_FUNCTIONAPP_NAME}}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  grant-permissions:
    runs-on: ubuntu-latest # For Linux, use ubuntu-latest
    environment: dev
    needs: build-reusable
    steps:      
      - name: 'Sql Migration'
        uses: azure/sql-action@v2.3
        with:
          connection-string: ${{ env.CONNECTION_STRING }}
          path: ./SqlManagedIdentity/Migration1.sql

      - name: 'Generate Sql Script to grant permissions'
        uses: azure/powershell@v2
        with:
          azPSVersion: 'latest'
          inlineScript: ./SqlManagedIdentity/Deployment//GenerateSqlScript.ps1 -appName "func-cus" -principalId '${{ steps.bicep_deployment.outputs.functionPrincipalId }}'

      - name: 'Run Sql Script to grant permissions'
        uses: azure/sql-action@v2.3
        with:
          connection-string: ${{ env.CONNECTION_STRING }}
          path: ./SqlManagedIdentity/Deployment/func-cus-GrantPermissions.sql