name: Deploy DotNet project to Azure Function App

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  AZURE_FUNCTIONAPP_NAME: 'func-cus'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'SqlManagedIdentity'
  CONNECTION_STRING: 'Server=tcp:sqlmanagedidentitycus.database.windows.net,1433;Initial Catalog=todo;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;Authentication="Active Directory Default";'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and Deploy Function App'
        id: build_and_deploy
        uses: ./.github/actions/build-and-deploy
        with:
          AZURE_FUNCTIONAPP_PACKAGE_PATH: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          AZURE_FUNCTIONAPP_NAME: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          DOTNET_VERSION: ${{ vars.DOTNET_VERSION }}

      - name: 'Sql Migration'
        uses: azure/sql-action@v2.3
        with:
          connection-string: ${{ env.CONNECTION_STRING }}
          path: ./SqlManagedIdentity/Migration1.sql

      - name: 'Generate Sql Script to grant permissions'
        uses: azure/powershell@v2
        with:
          azPSVersion: 'latest'
          inlineScript: |
            ./SqlManagedIdentity/Deployment/GenerateSqlScript.ps1 -appName "${{ env.AZURE_FUNCTIONAPP_NAME }}" -principalId '${{ steps.build_and_deploy.outputs.functionPrincipalId }}'

      - name: 'Run Sql Script to grant permissions'
        uses: azure/sql-action@v2.3
        with:
          connection-string: ${{ env.CONNECTION_STRING }}
          path: ./SqlManagedIdentity/Deployment/${{ env.AZURE_FUNCTIONAPP_NAME }}-GrantPermissions.sql