on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
    outputs:
      result:
        value: ${{ jobs.my_job.outputs.output_message }}
    secrets:
      MY_SECRET:
        required: true
jobs:
  my_job:
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      functionAppId: ${{ steps.greet.outputs.greeting }}
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Login via Azure CLI'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup DotNet ${{ vars.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash # For Linux, use bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
          
      - name: Deploy Bicep file
        id: bicep_deployment
        uses: azure/arm-deploy@v2
        with:
          template: ./SqlManagedIdentity/Deployment/deploy.bicep
          failOnStdErr: false
          scope: 'subscription'
          region: 'Central US'

      - name: Use Bicep Outputs
        run: |
          echo "Function App Id: ${{ steps.bicep_deployment.outputs.functionPrincipalId }}"        

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'          